// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_App;

#nullable disable

namespace To_Do_App.Migrations
{
    [DbContext(typeof(ToDoApp_DbContext))]
    [Migration("20250716230828_some-edits")]
    partial class someedits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("To_Do_App.Model.Lookup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("MajorCode")
                        .HasColumnType("int");

                    b.Property<int>("MinorCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MajorCode = 0,
                            MinorCode = 0,
                            Name = "Priority"
                        },
                        new
                        {
                            Id = 2L,
                            MajorCode = 0,
                            MinorCode = 1,
                            Name = "High"
                        },
                        new
                        {
                            Id = 3L,
                            MajorCode = 0,
                            MinorCode = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 4L,
                            MajorCode = 0,
                            MinorCode = 3,
                            Name = "Low"
                        });
                });

            modelBuilder.Entity("To_Do_App.Model.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PriorityId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("isComplete")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("To_Do_App.Model.TaskItem", b =>
                {
                    b.HasOne("To_Do_App.Model.Lookup", "lookup")
                        .WithMany()
                        .HasForeignKey("PriorityId");

                    b.Navigation("lookup");
                });
#pragma warning restore 612, 618
        }
    }
}
